[[custom_groups]]
name = "🔰 节点选择"
type = "select"
rule = [".*"]

[[custom_groups]]
name = "👥 社交平台"
type = "select"
rule = ["(家)", ".*"]

[[custom_groups]]
name = "🎬 全球媒体"
type = "select"
rule = ["(家)", ".*"]

[[custom_groups]]
name = "🤖 人工智能"
type = "select"
rule = ["(家)", ".*"]

[[custom_groups]]
name = "📲 即时通讯"
type = "select"
rule = [".*"]

[[custom_groups]]
name = "🍎 系统平台"
type = "select"
rule = ["[]🎯 直接连接", ".*"]

[[custom_groups]]
name = "🎮 游戏下载"
type = "select"
rule = ["[]🎯 直接连接", ".*"]

[[custom_groups]]
name = "🎯 直接连接"
type = "select"
rule = ["[]DIRECT", "[]🔰 节点选择"]

[[custom_groups]]
name = "🛑 广告拦截"
type = "select"
rule = ["[]REJECT", "[]🎯 直接连接", "[]🔰 节点选择"]

[[custom_groups]]
name = "🐟 漏网之鱼"
type = "select"
rule = ["[]🔰 节点选择"]