[[rulesets]]
group = "🛑 广告拦截"
ruleset = "rules/AdBlock.list"

[[rulesets]]
group = "🎯 直接连接"
ruleset = "rules/DirectConnect.list"

[[rulesets]]
group = "👥 社交平台"
ruleset = "rules/SocialMedia.list"

[[rulesets]]
group = "🎬 全球媒体"
ruleset = "rules/GlobalMedia.list"

[[rulesets]]
group = "🤖 人工智能"
ruleset = "rules/AI.list"

[[rulesets]]
group = "🎮 游戏下载"
ruleset = "rules/GameDownload.list"

[[rulesets]]
group = "🍎 系统平台"
ruleset = "rules/System.list"

[[rulesets]]
group = "📲 即时通讯"
ruleset = "rules/IM.list"

[[rulesets]]
group = "🔰 节点选择"
ruleset = "rules/NodePick.list"

[[rulesets]]
group = "🐟 漏网之鱼"
ruleset = "[]FINAL"